/*
 * Cette classe est de type Frame, elle va nous permettre d'améliorer le jeu à 
 * à l'aide d'une interface graphique.
 */
package superpuissance4_guttadoro_prouillet;

import java.util.Random;
import java.util.Scanner;

/**
 *
 * @author Rosanna Guttadoro
 */
public class FenetreDeJeu extends javax.swing.JFrame {
    
    
    Joueur[] ListeJoueurs = new Joueur[2]; //on lui donne les attributs nécessaires
    Jeton[] ListeJetons = new Jeton[21];
    Joueur joueurCourant;
    Grille grillePartie = new Grille(); 
    Jeton jetonCourant;
    
    public FenetreDeJeu() {
        initComponents(); // avant tout on initialise les composants
        panneauInfosPartie.setVisible(false); 
        //On cache les deux panneaux d'infos avant le début de la partie
        panneauCreationPartie.setVisible(false);
        
        for ( int i=0 ; i <=5; i++ ) {
            for ( int j=0 ; j <7 ; j++ ) {
                CelluleGraphique cellGraph = new CelluleGraphique(grillePartie.Cellules[i][j]);
                panneauGrille.add(cellGraph); 
                // Ajout des cellules graphique dans le panneau associé : la grille
            }
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panneauGrille = new javax.swing.JPanel();
        panneauInfosJoueurs = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Nom_Joueur2 = new javax.swing.JTextField();
        btm_start = new javax.swing.JButton();
        Nom_Joueur1 = new javax.swing.JTextField();
        panneauInfosPartie = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lbl_j1desint = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lbl_j1nom = new javax.swing.JLabel();
        lbl_j1couleur = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbl_j2desint = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lbl_j2couleur = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lbl_j2nom = new javax.swing.JLabel();
        panneauCreationPartie = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbl_jcourant = new javax.swing.JLabel();
        messages = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        btm_col6 = new javax.swing.JButton();
        btm_col2 = new javax.swing.JButton();
        btm_col3 = new javax.swing.JButton();
        btm_col4 = new javax.swing.JButton();
        btm_col1 = new javax.swing.JButton();
        btm_col0 = new javax.swing.JButton();
        btm_col5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panneauGrille.setBackground(new java.awt.Color(204, 204, 255));
        panneauGrille.setLayout(new java.awt.GridLayout(6, 7));
        getContentPane().add(panneauGrille, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 672, 576));

        panneauInfosJoueurs.setBackground(new java.awt.Color(255, 204, 204));
        panneauInfosJoueurs.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nom Joueur 2 :");
        panneauInfosJoueurs.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 100, 20));

        jLabel2.setText("Nom Joueur 1 :");
        panneauInfosJoueurs.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        Nom_Joueur2.setText("jTextField1");
        Nom_Joueur2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nom_Joueur2ActionPerformed(evt);
            }
        });
        panneauInfosJoueurs.add(Nom_Joueur2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, -1, -1));

        btm_start.setText("Démarrer Partie");
        btm_start.setActionCommand("Démarrer partie");
        btm_start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btm_startActionPerformed(evt);
            }
        });
        panneauInfosJoueurs.add(btm_start, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, -1, -1));

        Nom_Joueur1.setText("jTextField1");
        Nom_Joueur1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nom_Joueur1ActionPerformed(evt);
            }
        });
        panneauInfosJoueurs.add(Nom_Joueur1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        getContentPane().add(panneauInfosJoueurs, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 90, 330, 110));

        panneauInfosPartie.setBackground(new java.awt.Color(255, 204, 204));
        panneauInfosPartie.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("Désintégrateur :");
        panneauInfosPartie.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 100, 30));

        lbl_j1desint.setText("nbdesintjoueur1");
        panneauInfosPartie.add(lbl_j1desint, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 100, 30));

        jLabel6.setText("Couleur :");
        panneauInfosPartie.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 70, 30));

        lbl_j1nom.setText("nomjoueur1");
        panneauInfosPartie.add(lbl_j1nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 70, 30));

        lbl_j1couleur.setText("couleurjoueur1");
        panneauInfosPartie.add(lbl_j1couleur, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 100, 30));

        jLabel5.setText("Désintégrateur :");
        panneauInfosPartie.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 100, 30));

        lbl_j2desint.setText("nbdesintjoueur2");
        panneauInfosPartie.add(lbl_j2desint, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 100, 30));

        jLabel8.setText("Couleur :");
        panneauInfosPartie.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 70, 30));

        jLabel9.setText("Joueur 2 :");
        panneauInfosPartie.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 70, 30));

        lbl_j2couleur.setText("couleurjoueur2");
        panneauInfosPartie.add(lbl_j2couleur, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 100, 30));
        panneauInfosPartie.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 102, 270, 0));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Infos Partie :");
        panneauInfosPartie.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 90, 30));

        jLabel11.setText("Joueur 1 :");
        panneauInfosPartie.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 70, 30));

        lbl_j2nom.setText("nomjoueur2");
        panneauInfosPartie.add(lbl_j2nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 70, 30));

        getContentPane().add(panneauInfosPartie, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 230, 310, 210));

        panneauCreationPartie.setBackground(new java.awt.Color(255, 204, 204));
        panneauCreationPartie.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Infos Jeu :");
        panneauCreationPartie.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 90, 30));

        jLabel7.setText("Joueur Courant :");
        panneauCreationPartie.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 100, 30));

        lbl_jcourant.setText("nomjoueur");
        panneauCreationPartie.add(lbl_jcourant, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 70, 30));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        messages.setViewportView(jTextArea1);

        panneauCreationPartie.add(messages, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 290, 90));

        getContentPane().add(panneauCreationPartie, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 470, 310, 180));

        btm_col6.setText("7");
        btm_col6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btm_col6ActionPerformed(evt);
            }
        });
        getContentPane().add(btm_col6, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 60, -1, -1));

        btm_col2.setText("3");
        btm_col2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btm_col2ActionPerformed(evt);
            }
        });
        getContentPane().add(btm_col2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, -1, -1));

        btm_col3.setText("4");
        btm_col3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btm_col3ActionPerformed(evt);
            }
        });
        getContentPane().add(btm_col3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, -1, -1));

        btm_col4.setText("5");
        btm_col4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btm_col4ActionPerformed(evt);
            }
        });
        getContentPane().add(btm_col4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 60, -1, -1));

        btm_col1.setText("2");
        btm_col1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btm_col1ActionPerformed(evt);
            }
        });
        getContentPane().add(btm_col1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, -1, -1));

        btm_col0.setText("1");
        btm_col0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btm_col0ActionPerformed(evt);
            }
        });
        getContentPane().add(btm_col0, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        btm_col5.setText("6");
        btm_col5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btm_col5ActionPerformed(evt);
            }
        });
        getContentPane().add(btm_col5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 60, -1, -1));

        setBounds(0, 0, 1069, 683);
    }// </editor-fold>//GEN-END:initComponents

    private void Nom_Joueur2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nom_Joueur2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Nom_Joueur2ActionPerformed

    private void Nom_Joueur1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nom_Joueur1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Nom_Joueur1ActionPerformed

    private void btm_col0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btm_col0ActionPerformed
        // TODO add your handling code here:
        JouerDansColonne(0);
        if (grillePartie.colonneRemplie(0)== true) btm_col0.setEnabled(false);
        joueurSuivant();
    }//GEN-LAST:event_btm_col0ActionPerformed

    private void btm_col6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btm_col6ActionPerformed
        // TODO add your handling code here:
        JouerDansColonne(6);
        if (grillePartie.colonneRemplie(6)== true) btm_col6.setEnabled(false);
        joueurSuivant();
    }//GEN-LAST:event_btm_col6ActionPerformed

    private void btm_startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btm_startActionPerformed
        panneauInfosPartie.setVisible(true);
        panneauCreationPartie.setVisible(true);
        initialiserPartie();
        panneauGrille.repaint();
        btm_start.setEnabled(false);
    }//GEN-LAST:event_btm_startActionPerformed

    private void btm_col1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btm_col1ActionPerformed
        // TODO add your handling code here:
        JouerDansColonne(1);
        if (grillePartie.colonneRemplie(1)== true) btm_col1.setEnabled(false);
        joueurSuivant();
    }//GEN-LAST:event_btm_col1ActionPerformed

    private void btm_col2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btm_col2ActionPerformed
        // TODO add your handling code here:
        JouerDansColonne(2);
        if (grillePartie.colonneRemplie(2)== true) btm_col2.setEnabled(false);
        joueurSuivant();
    }//GEN-LAST:event_btm_col2ActionPerformed

    private void btm_col3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btm_col3ActionPerformed
        // TODO add your handling code here:
        JouerDansColonne(3);
        if (grillePartie.colonneRemplie(3)== true) btm_col3.setEnabled(false);
        joueurSuivant();
    }//GEN-LAST:event_btm_col3ActionPerformed

    private void btm_col4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btm_col4ActionPerformed
        // TODO add your handling code here:
        JouerDansColonne(4);
        if (grillePartie.colonneRemplie(4)== true) btm_col4.setEnabled(false);
        joueurSuivant();
    }//GEN-LAST:event_btm_col4ActionPerformed

    private void btm_col5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btm_col5ActionPerformed
        // TODO add your handling code here:
        JouerDansColonne(5);
        if (grillePartie.colonneRemplie(5)== true) btm_col5.setEnabled(false);
        joueurSuivant();
    }//GEN-LAST:event_btm_col5ActionPerformed

    
    public void joueurSuivant() {
        

        
        if ( joueurCourant == ListeJoueurs[0]) {
            joueurCourant=ListeJoueurs[1];
            
        } else {
            joueurCourant=ListeJoueurs[0];
          
        }
        lbl_jcourant.setText(joueurCourant.Nom);
  
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FenetreDeJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FenetreDeJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FenetreDeJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FenetreDeJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FenetreDeJeu().setVisible(true);
            }
        });
    }
    
     public void initialiserPartie() {
        
        
        // nous avions vu que dans la classe grille, pour chaque nouvelle partie il fallait vider la grille :
        
        
        //CREATION DE LA GRILLE
        //composé la grille avec des désintégrateurs et trou noir placé aléatoirement
        int [] positionsTrounoir = new int[4];
        for (int i = 0; i<positionsTrounoir.length; i++) {
            //génére un tableau de 4 entiers aléatoire
            Random a = new Random();
            positionsTrounoir[i] = a.nextInt(6);
            //System.out.print(positionsTrounoir[i]); 
            }
        
        for (int j = 0; j<2; j++) { //crée 3 différents Trous noirs
            grillePartie.placerTrouNoir(positionsTrounoir[j],positionsTrounoir[j+1]);
            
        } 
        int [] positionsDesing = new int[4];
        for (int i = 0; i<positionsDesing.length; i++) {
            //génére un tableau de 4 entiers aléatoire
            Random a = new Random();
            positionsDesing[i] = a.nextInt(6);
            //System.out.print(positionsDesing[i]); 
            }
        
        for (int j = 0; j<2; j++) { //crée 3 différents désintégrateurs sur la grille
            grillePartie.placerDesintegrateur(positionsDesing[j],positionsDesing[j+1]);
            
        } 
        
        //INFOS DEBUT DU JEU:
        String nomJ1 = Nom_Joueur1.getText();
        Joueur Joueur1 = new  Joueur(nomJ1); 
        // on initialise les joueurs en récupérant les noms saisis dans les cases
        ListeJoueurs[0]= Joueur1;
        
        String nomJ2 = Nom_Joueur2.getText();
        Joueur Joueur2 = new  Joueur(nomJ2); 
        
        ListeJoueurs[1]= Joueur2;
        
        attribuerCouleursAuxJoueurs(); //définition des couleurs
        
        // on donne des jetons aux joueurs de la couleur qu'il faut
        for ( int i=0 ; i<=20 ; i++) {
            Jeton Jeton1 = new Jeton(Joueur1.couleur);
            Jeton Jeton2 = new Jeton(Joueur2.couleur);
            Joueur1.ajouterJeton(Jeton1);
            Joueur2.ajouterJeton(Jeton2);
        }
        
        // on l'affiche pour permettre aux joueurs de connaitre leur couleur 
        //System.out.println(Joueur1.Nom +" a la couleur "+Joueur1.couleur);
        //System.out.println(Joueur2.Nom +" a la couleur "+Joueur2.couleur);
        
        //PANNEAU INFO JOUEUR:
        lbl_j1nom.setText(nomJ1); //Permets l'affichage des noms sur le pannel
        lbl_j2nom.setText(nomJ2);
        lbl_j1couleur.setText(Joueur1.couleur); //Puis de leur couleur respective
        lbl_j2couleur.setText(Joueur2.couleur);
        lbl_j1desint.setText(Joueur1.nombreDesintegrateurs+""); 
        lbl_j2desint.setText(Joueur2.nombreDesintegrateurs+"");
        //Les guillemets vide permettent d'écrire le nbDesintégrateur qui est un int en tant que string
        
        
        
        //PANNEAU INFO PARTIE:
        // on détermine qui sera le premier joueur de la meme facon que pour attribuer les couleurs
        Random random = new Random();
        boolean premier_joueur = random.nextBoolean();
        if ( premier_joueur==true ) {
            joueurCourant=ListeJoueurs[0];
        } else {
            joueurCourant = ListeJoueurs[1];
        }
        lbl_jcourant.setText(joueurCourant.Nom);
        
        
    
        
    }
     
     public boolean JouerDansColonne ( int indice_colonne ) {
          
        
        
        grillePartie.ajouterJetondansColonne(joueurCourant.ListeJetons[joueurCourant.nombreJetons_restants-1] , indice_colonne );
        
        panneauGrille.repaint();
        grillePartie.afficherGrilleSurConsole();
        return true;
      
    }
     
     
     public void  attribuerCouleursAuxJoueurs ( ) {
        // l'atribution de la couleur se fait de manière aléatoire 
        Random rand = new Random(); 
        boolean couleur;
        couleur = rand.nextBoolean(); 
        if ( couleur == true ) {
            ListeJoueurs[0].couleur="jaune"; 
            ListeJoueurs[1].couleur="rouge"; 
            
        } else {
            ListeJoueurs[0].couleur="rouge";
            ListeJoueurs[1].couleur="jaune";
        }
         
    }
    
//List des composants de la frame, qui s'ajoute automatiquement
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Nom_Joueur1;
    private javax.swing.JTextField Nom_Joueur2;
    private javax.swing.JButton btm_col0;
    private javax.swing.JButton btm_col1;
    private javax.swing.JButton btm_col2;
    private javax.swing.JButton btm_col3;
    private javax.swing.JButton btm_col4;
    private javax.swing.JButton btm_col5;
    private javax.swing.JButton btm_col6;
    private javax.swing.JButton btm_start;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lbl_j1couleur;
    private javax.swing.JLabel lbl_j1desint;
    private javax.swing.JLabel lbl_j1nom;
    private javax.swing.JLabel lbl_j2couleur;
    private javax.swing.JLabel lbl_j2desint;
    private javax.swing.JLabel lbl_j2nom;
    private javax.swing.JLabel lbl_jcourant;
    private javax.swing.JScrollPane messages;
    private javax.swing.JPanel panneauCreationPartie;
    private javax.swing.JPanel panneauGrille;
    private javax.swing.JPanel panneauInfosJoueurs;
    private javax.swing.JPanel panneauInfosPartie;
    // End of variables declaration//GEN-END:variables
}
