/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package superpuissance4_guttadoro_prouillet;

/**
 *
 * @author Rosanna Guttadoro
 */
public class FenetreDeJeu extends javax.swing.JFrame {

    /**
     * Creates new form FenetreDeJeu
     */
    public FenetreDeJeu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panneauGrille = new javax.swing.JPanel();
        panneauInfoJoueurs = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Nom_Joueur2 = new javax.swing.JTextField();
        btm_start = new javax.swing.JButton();
        Nom_Joueur1 = new javax.swing.JTextField();
        panneauInfosPartie = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lbl_j1desint = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lbl_j1nom = new javax.swing.JLabel();
        lbl_j1couleur = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbl_j2desint = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lbl_j2couleur = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lbl_j2nom1 = new javax.swing.JLabel();
        panneauCreationPartie = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbl_jcourant = new javax.swing.JLabel();
        messages = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        btm_col6 = new javax.swing.JButton();
        btm_col2 = new javax.swing.JButton();
        btm_col3 = new javax.swing.JButton();
        btm_col4 = new javax.swing.JButton();
        btm_col1 = new javax.swing.JButton();
        btm_col0 = new javax.swing.JButton();
        btm_col5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panneauGrille.setBackground(new java.awt.Color(0, 102, 204));
        panneauGrille.setLayout(new java.awt.GridLayout(6, 7));
        getContentPane().add(panneauGrille, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 672, 576));

        panneauInfoJoueurs.setBackground(new java.awt.Color(255, 204, 204));
        panneauInfoJoueurs.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nom Joueur 2 :");
        panneauInfoJoueurs.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 80, 20));

        jLabel2.setText("Nom Joueur 1 :");
        panneauInfoJoueurs.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        Nom_Joueur2.setText("jTextField1");
        Nom_Joueur2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nom_Joueur2ActionPerformed(evt);
            }
        });
        panneauInfoJoueurs.add(Nom_Joueur2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, -1, -1));

        btm_start.setText("Démarrer Partie");
        btm_start.setActionCommand("Démarrer partie");
        panneauInfoJoueurs.add(btm_start, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, -1, -1));

        Nom_Joueur1.setText("jTextField1");
        Nom_Joueur1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nom_Joueur1ActionPerformed(evt);
            }
        });
        panneauInfoJoueurs.add(Nom_Joueur1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, -1));

        getContentPane().add(panneauInfoJoueurs, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 90, 310, 110));

        panneauInfosPartie.setBackground(new java.awt.Color(255, 204, 204));
        panneauInfosPartie.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("Désintégrateur :");
        panneauInfosPartie.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 100, 30));

        lbl_j1desint.setText("nbdesintjoueur1");
        panneauInfosPartie.add(lbl_j1desint, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 100, 30));

        jLabel6.setText("Couleur :");
        panneauInfosPartie.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 70, 30));

        lbl_j1nom.setText("nomjoueur1");
        panneauInfosPartie.add(lbl_j1nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 70, 30));

        lbl_j1couleur.setText("couleurjoueur1");
        panneauInfosPartie.add(lbl_j1couleur, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 100, 30));

        jLabel5.setText("Désintégrateur :");
        panneauInfosPartie.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 100, 30));

        lbl_j2desint.setText("nbdesintjoueur2");
        panneauInfosPartie.add(lbl_j2desint, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 100, 30));

        jLabel8.setText("Couleur :");
        panneauInfosPartie.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 70, 30));

        jLabel9.setText("Joueur 2 :");
        panneauInfosPartie.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 70, 30));

        lbl_j2couleur.setText("couleurjoueur2");
        panneauInfosPartie.add(lbl_j2couleur, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 100, 30));
        panneauInfosPartie.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 102, 270, 0));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Infos Partie :");
        panneauInfosPartie.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 90, 30));

        jLabel11.setText("Joueur 1 :");
        panneauInfosPartie.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 70, 30));

        lbl_j2nom1.setText("nomjoueur2");
        panneauInfosPartie.add(lbl_j2nom1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 70, 30));

        getContentPane().add(panneauInfosPartie, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 230, 310, 210));

        panneauCreationPartie.setBackground(new java.awt.Color(255, 204, 204));
        panneauCreationPartie.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Infos Jeu :");
        panneauCreationPartie.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 90, 30));

        jLabel7.setText("Joueur Courant :");
        panneauCreationPartie.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 100, 30));

        lbl_jcourant.setText("nomjoueur");
        panneauCreationPartie.add(lbl_jcourant, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 70, 30));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        messages.setViewportView(jTextArea1);

        panneauCreationPartie.add(messages, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 290, 90));

        getContentPane().add(panneauCreationPartie, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 470, 310, 180));

        btm_col6.setText("7");
        btm_col6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btm_col6ActionPerformed(evt);
            }
        });
        getContentPane().add(btm_col6, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 60, -1, -1));

        btm_col2.setText("3");
        getContentPane().add(btm_col2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, -1, -1));

        btm_col3.setText("4");
        getContentPane().add(btm_col3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, -1, -1));

        btm_col4.setText("5");
        getContentPane().add(btm_col4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 60, -1, -1));

        btm_col1.setText("2");
        getContentPane().add(btm_col1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, -1, -1));

        btm_col0.setText("1");
        btm_col0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btm_col0ActionPerformed(evt);
            }
        });
        getContentPane().add(btm_col0, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        btm_col5.setText("6");
        getContentPane().add(btm_col5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 60, -1, -1));

        setBounds(0, 0, 1069, 683);
    }// </editor-fold>//GEN-END:initComponents

    private void Nom_Joueur2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nom_Joueur2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Nom_Joueur2ActionPerformed

    private void Nom_Joueur1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nom_Joueur1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Nom_Joueur1ActionPerformed

    private void btm_col0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btm_col0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btm_col0ActionPerformed

    private void btm_col6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btm_col6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btm_col6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FenetreDeJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FenetreDeJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FenetreDeJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FenetreDeJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FenetreDeJeu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Nom_Joueur1;
    private javax.swing.JTextField Nom_Joueur2;
    private javax.swing.JButton btm_col0;
    private javax.swing.JButton btm_col1;
    private javax.swing.JButton btm_col2;
    private javax.swing.JButton btm_col3;
    private javax.swing.JButton btm_col4;
    private javax.swing.JButton btm_col5;
    private javax.swing.JButton btm_col6;
    private javax.swing.JButton btm_start;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lbl_j1couleur;
    private javax.swing.JLabel lbl_j1desint;
    private javax.swing.JLabel lbl_j1nom;
    private javax.swing.JLabel lbl_j2couleur;
    private javax.swing.JLabel lbl_j2desint;
    private javax.swing.JLabel lbl_j2nom1;
    private javax.swing.JLabel lbl_jcourant;
    private javax.swing.JScrollPane messages;
    private javax.swing.JPanel panneauCreationPartie;
    private javax.swing.JPanel panneauGrille;
    private javax.swing.JPanel panneauInfoJoueurs;
    private javax.swing.JPanel panneauInfosPartie;
    // End of variables declaration//GEN-END:variables
}
